name: train_hard_reborn
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  percent_indicator: ^4.2.4
  fl_chart: ^0.70.2
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  numberpicker: ^2.1.2
  provider: ^6.1.4
  http: ^1.3.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  firebase_storage: ^12.4.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/community.svg
    - assets/images/nutrion.svg
    - assets/images/tracker.svg
    - assets/images/training.svg

  uses-material-design: true
