// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qElE2TAWzLQJXbn-m2lpVk0TLVhPod8',
    appId: '1:780165492384:web:00afb1f8d2f8b9673423c5',
    messagingSenderId: '780165492384',
    projectId: 'trainhard-reborn',
    authDomain: 'trainhard-reborn.firebaseapp.com',
    storageBucket: 'trainhard-reborn.firebasestorage.app',
    measurementId: 'G-NPEQZK3KJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3X6IthMXeT-isPn23g-4-2xGeVHk-_v0',
    appId: '1:780165492384:android:961c93f52791c3533423c5',
    messagingSenderId: '780165492384',
    projectId: 'trainhard-reborn',
    storageBucket: 'trainhard-reborn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQRzftmGCA7yxeRTykonjKJ_CJQDTrfq4',
    appId: '1:780165492384:ios:770041db33b836013423c5',
    messagingSenderId: '780165492384',
    projectId: 'trainhard-reborn',
    storageBucket: 'trainhard-reborn.firebasestorage.app',
    iosBundleId: 'com.trainhard.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQRzftmGCA7yxeRTykonjKJ_CJQDTrfq4',
    appId: '1:780165492384:ios:c89fb80eb2de7b313423c5',
    messagingSenderId: '780165492384',
    projectId: 'trainhard-reborn',
    storageBucket: 'trainhard-reborn.firebasestorage.app',
    iosBundleId: 'com.example.trainHardReborn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9qElE2TAWzLQJXbn-m2lpVk0TLVhPod8',
    appId: '1:780165492384:web:4cc23abd23b16e9e3423c5',
    messagingSenderId: '780165492384',
    projectId: 'trainhard-reborn',
    authDomain: 'trainhard-reborn.firebaseapp.com',
    storageBucket: 'trainhard-reborn.firebasestorage.app',
    measurementId: 'G-4641J8GJ4Y',
  );
}
